"""empty message

Revision ID: 288edd42bc6c
Revises: e09503250453
Create Date: 2024-03-31 10:11:54.917785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288edd42bc6c'
down_revision = 'e09503250453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
