"""some message

Revision ID: 919abf07e874
Revises: 96d570084b1d
Create Date: 2024-03-25 18:02:30.458009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919abf07e874'
down_revision = '96d570084b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
